FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt update && apt install -y \
    cmake \
    ninja-build \
    clang \
    clang-format \
    clang-tidy \
    clang-tools \
    llvm \
    cppcheck \
    valgrind \
    doxygen \
    graphviz \
    ccache \
    libssl-dev \
    libwxgtk3.2-dev \
    libgtk-3-dev \
    pkg-config
