option(ENABLE_ASAN "Enable AddressSanitizer (ASan)" ON)

function(AddASanInstrumentation target)
    if(ENABLE_ASAN)
        if(MSVC)
            target_compile_options("${target}" PRIVATE /fsanitize=address)
            target_link_options("${target}" PRIVATE /fsanitize=address)
        else()
            target_compile_options("${target}" PRIVATE -fsanitize=address -fno-omit-frame-pointer)
            target_link_options("${target}" PRIVATE -fsanitize=address)
        endif()
    endif()
endfunction()