function(AddASanInstrumentation)
    if(ENABLE_ASAN)
        if(WIN32)
            message(STATUS "AddressSanitizer (ASan): Disabled on Windows")
        else()
            message(STATUS "AddressSanitizer (ASan): Applying global configuration")
            add_compile_options(-fsanitize=address -fno-omit-frame-pointer)
            add_link_options(-fsanitize=address)
        endif()
    endif()
endfunction()
