if(ENABLE_CCACHE)
    find_program(CCACHE_BIN ccache)
    if(CCACHE_BIN)
        message(STATUS "ccache found: ${CCACHE_BIN}")
        set(CMAKE_C_COMPILER_LAUNCHER   "${CCACHE_BIN}" CACHE STRING "C launcher")
        set(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_BIN}" CACHE STRING "C++ launcher")
    else()
        message(STATUS "ccache not found")
    endif()
endif()
