macro(ConfigModule target)
    AddCppCheck("${target}")
    AddClangTidy("${target}")
    InstrumentForCoverage("${target}")
endmacro()

macro(ConfigTest target)
    AddTests("${target}")
    AddInstrumentation("${target}")
    CleanCoverage("${target}")
    AddCoverage("${target}")
endmacro()
