macro(ConfigModule target)
    FormatModule("${target}")
    AddCppCheck("${target}")
    AddClangTidy("${target}")
    InstrumentForCoverage("${target}")
endmacro()

macro(ConfigTest target)
    FormatTest("${target}")
    AddTests("${target}")
endmacro()
