macro(ConfigModule target)
    FormatModule("${target}")
    AddCppCheck("${target}")
    AddClangTidy("${target}")
    InstrumentForCoverage("${target}")
endmacro()

macro(ConfigTest target)
    FormatTest("${target}")
    AddTests("${target}")
    AddInstrumentation("${target}")
    CleanCoverage("${target}")
    AddCoverage("${target}")
endmacro()

macro(ConfigInterface target)
    FormatInterface("${target}")
    AddCppCheck("${target}")
    AddClangTidy("${target}")
endmacro()

macro(ConfigTestInterface target)
    FormatTest("${target}")
    AddTests("${target}")
    AddInstrumentation("${target}")
    InstrumentForCoverage("${target}")
    CleanCoverage("${target}")
    AddCoverage("${target}")
endmacro()
