include(Valgrind)
include(AddressSanitizer)

function(AddInstrumentation target)
    if(ENABLE_ASAN AND ENABLE_VALGRIND)
        message(FATAL_ERROR "Conflict: Cannot enable ASan and Valgrind at the same time")
    elseif(ENABLE_ASAN)
        AddASanInstrumentation("${target}")
    elseif(ENABLE_VALGRIND)
        AddValgrindInstrumentation("${target}")
    else()
        message(STATUS "No dynamic instrumentation enabled for: ${target}")
    endif()
endfunction()
